import { CaseData, ReplyData, CommentData } from "./CaseData";

export const dummyCases: CaseData[] = [
  {
    id: 1,
    patient_id: 101,
    title: "Headache and fever",
    description: "Patient has been experiencing headache for 2 days",
    created_at: "2026-04-02",
    status: "Under Review",
    isEmergency: false,
  },
  {
    id: 2,
    patient_id: 102,
    title: "Skin Rash",
    description: "Red rash on arms",
    created_at: "2026-04-01",
    status: "Doctor Replied",
    isEmergency: true,
  },
  {
    id: 3,
    patient_id: 103,
    title: "Skin Rash",
    description: "Red rash on arms",
    created_at: "2026-04-01",
    status: "Resolved",
    isEmergency: false,
  },
  {
    id: 4,
    patient_id: 104,
    title: "Headache and fever",
    description: "Patient has been experiencing headache for 2 days",
    created_at: "2026-04-02",
    status: "Under Review",
    isEmergency: false,
  },
  {
    id: 5,
    patient_id: 105,
    title: "Skin Rash",
    description: "Red rash on arms",
    created_at: "2026-04-01",
    status: "Doctor Replied",
    isEmergency: true,
  },
  {
    id: 6,
    patient_id: 106,
    title: "Skin Rash",
    description: "Red rash on arms",
    created_at: "2026-04-01",
    status: "Resolved",
    isEmergency: false,
  },
  {
    id: 7,
    patient_id: 107,
    title: "Headache and fever",
    description: "Patient has been experiencing headache for 2 days",
    created_at: "2026-04-02",
    status: "Under Review",
    isEmergency: false,
  },
  {
    id: 8,
    patient_id: 108,
    title: "Skin Rash",
    description: "Red rash on arms",
    created_at: "2026-04-01",
    status: "Doctor Replied",
    isEmergency: true,
  },
  {
    id: 9,
    patient_id: 109,
    title: "Skin Rash",
    description: "Red rash on arms",
    created_at: "2026-04-01",
    status: "Resolved",
    isEmergency: false,
  },
  {
    id: 10,
    patient_id: 110,
    title: "Headache and fever",
    description: "Patient has been experiencing headache for 2 days",
    created_at: "2026-04-02",
    status: "Under Review",
    isEmergency: false,
  },
  {
    id: 11,
    patient_id: 111,
    title: "Skin Rash",
    description: "Red rash on arms",
    created_at: "2026-04-01",
    status: "Doctor Replied",
    isEmergency: true,
  },
  {
    id: 12,
    patient_id: 112,
    title: "Skin Rash",
    description: "Red rash on arms",
    created_at: "2026-04-01",
    status: "Resolved",
    isEmergency: false,
  },
];

export const allDummyReplies: ReplyData[] = [
  {
    id: "1",
    case_id: 1,
    title: "Dr. Sarah Ahmed",
    major: "Clinical Psychologist",
    message: "Based on the symptoms you described, I recommend starting with cognitive behavioral therapy techniques for sleep. I'll send you a detailed plan soon.",
    time: "2 hours ago",
  },
  {
    id: "2",
    case_id: 1,
    title: "Dr. Sarah Ahmed",
    major: "Clinical Psychologist",
    message: "Make sure you drink chamomile tea before going to bed tonight.",
    time: "Just now",
  },
  {
    id: "3",
    case_id: 2,
    title: "Dr. Khaled Youssef",
    major: "Dermatologist",
    message: "Please avoid using any scented soaps and apply aloe vera for the rash.",
    time: "1 hour ago",
  },
  {
    id: "4",
    case_id: 5,
    title: "Dr. Khaled Youssef",
    major: "Dermatologist",
    message: "I reviewed your images. Can you provide more details if it's itchy?",
    time: "30 mins ago",
  },
];

export const allDummyComments: CommentData[] = [
  {
    id: "1",
    reply_id: "1",
    title: "You",
    description: "I have tried that, but it doesn't seem to help much.",
    time: "Just now",
    major: "Patient",
  },
  {
    id: "2",
    reply_id: "1",
    title: "You",
    description: "Could you send a more detailed plan on how to start?",
    time: "Just now",
    major: "Patient",
  },
  {
    id: "3",
    reply_id: "2",
    title: "You",
    description: "Should I drink chamomile tea cold or hot?",
    time: "1 hour ago",
    major: "Patient",
  },
  {
    id: "4",
    reply_id: "3",
    title: "You",
    description: "I'm uploading a clearer picture right now.",
    time: "Just now",
    major: "Patient",
  },
];
